version: '3'
services:
  app:
    build: "."
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: gross213
      MYSQL_DATABASE: oca
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: